import { createContext, useContext, useState } from 'react'

export const translations = {
  fr: {
    welcome: 'Bienvenue sur', appName: 'MoodTracker !',
    welcomeSub: 'Ton espace pour suivre comment tu te sens chaque jour.',
    login: 'Se connecter', register: "S'inscrire",
    email: 'Email', password: 'Mot de passe',
    loginBtn: 'Je vais aller mieux ❤️', back: '← Retour',
    firstname: 'Prénom', confirmPwd: 'Confirmer mot de passe',
    chooseLanguage: 'Choisir la langue / Choose language',
    moodQuestion: 'Comment tu te sens\naujourd\'hui ?',
    moodHint: 'Sélectionne ton humeur ↑',
    moodHappy: 'Tu es au top aujourd\'hui !',
    moodOk: 'Pas mal, ça va à peu près !',
    moodSad: 'Je suis là pour t\'écouter.',
    continueBtn: 'Continuer →', moreTellBtn: 'En dire plus', confideBtn: 'Me confier →',
    tooDayHappy: 'Aujourd\'hui tu es au top',
    alwaysCase: 'c\'est toujours le cas !',
    wantMoreInfo: 'tu veux m\'en dire plus ?',
    yes: 'Oui', no: 'Non',
    listeningTitle: 'Je t\'écoute', journalPH: 'Aujourd\'hui je...',
    tags: ['Sorti·e', 'Me suis fait plaisir', 'Mal dormi·e', 'Fait du sport', 'Au cinéma', 'Bonne nouvelle', 'Allé·e au travail', 'Fait le ménage', 'Cuisiné·e', 'Vu de la famille', 'Vu des ami·es', 'Temps pour moi', 'Pleuré·e', 'Anxieux·se', 'Fatigué·e', 'Pris mes médicaments', 'Médité·e', 'Lu un livre', 'Écouté de la musique'],
    thanksTitle: 'Merci pour ton retour',
    thanksSub: 'Tu peux toujours modifier ce moment dans le calendrier !',
    seeCalendar: 'Voir le calendrier',
    calendarTitle: 'Calendrier',
    months: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
    days: ['L','M','M','J','V','S','D'],
    legendGood: '🟢 Bien', legendOk: '🟡 Moyen', legendHard: '🔴 Difficile',
    calHint: 'Clique sur un jour pour voir le détail',
    editEntry: '✏️ Modifier', addEntry: '+ Ajouter',
    noComment: 'Aucun commentaire', notLogged: 'non renseigné', close: 'Fermer',
    editDay: 'Modifier le jour', addComment: 'Ajouter un commentaire...',
    cancel: 'Annuler', save: 'Sauvegarder',
    sleepLabel: 'Heures de sommeil', sleepQuestion: 'Tu as bien dormi ?', sleepSub: 'Combien d\'heures as-tu dormi cette nuit ?', skipBtn: 'Passer', avgSleep: 'Sommeil moyen',
    foodQuestion: 'Comment tu as mangé ?', foodSub: 'Ton alimentation d\'aujourd\'hui ?',
    foodLabel: 'Alimentation',
    foodOptions: [
      { value: 3, emoji: '🍽️', label: 'J\'ai bien mangé' },
      { value: 2, emoji: '🥗', label: 'J\'ai peu mangé' },
      { value: 1, emoji: '😔', label: 'Je n\'ai pas mangé' },
    ],
    fatigueQuestion: 'Comment est ton énergie ?', fatigueSub: 'Ton niveau de fatigue aujourd\'hui ?',
    fatigueLabel: 'Énergie',
    fatigueOptions: [
      { value: 3, emoji: '⚡', label: 'Pas fatigué·e' },
      { value: 2, emoji: '😌', label: 'Un peu fatigué·e' },
      { value: 1, emoji: '😓', label: 'Très fatigué·e' },
    ],
    statsTitle: 'Statistiques', daysTracked: 'Jours suivis',
    topMood: 'Humeur fréquente', positiveDays: 'Jours positifs', streak: 'Streak 🔥',
    thisWeek: '😊 Humeur cette semaine',
    daysShort: ['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'],
    moodLabel: 'Humeur',
    avgFoodLabel: 'Alimentation', avgFatigueLabel: 'Énergie',
    correlationChart: '📊 Humeur & bien-être',
    sleepCorrelationPos: '✨ Quand tu dors plus (≥7h), ton humeur est meilleure. Continue comme ça !',
    sleepCorrelationNeg: '🤔 Curieux — ton humeur semble meilleure avec moins de sommeil ce mois-ci.',
    sleepCorrelationNeutral: '📊 Pas de lien clair entre ton sommeil et ton humeur ce mois-ci.',
    foodCorrelationPos: '🍽️ Quand tu manges bien, ton humeur est généralement meilleure.',
    foodCorrelationNeg: '🤔 Curieux — ton humeur semble indépendante de ton alimentation ce mois-ci.',
    foodCorrelationNeutral: '📊 Pas de lien clair entre alimentation et humeur ce mois-ci.',
    fatigueCorrelationPos: '⚡ Quand tu es reposé·e, ton humeur est meilleure.',
    fatigueCorrelationNeg: '🤔 Ta fatigue ne semble pas affecter ton humeur ce mois-ci.',
    fatigueCorrelationNeutral: '📊 Pas de lien clair entre fatigue et humeur ce mois-ci.',
    chartTitle: 'Graphique', noData: '📋 Pas assez de données ce mois-ci.',
    trendHigh: '📊 Humeur globalement élevée ce mois-ci.',
    trendMid: '📊 Humeur plutôt stable et dans la moyenne.',
    trendLow: '📊 Quelques hauts et bas ce mois-ci.',
    trendHard: '📊 Mois difficile dans l\'ensemble.',
    trendUp: '↗ En progression sur la période.',
    trendDown: '↘ En baisse sur la période.',
    accountTitle: 'Mon compte', personalInfo: 'Informations personnelles',
    preferences: 'Préférences', privacy: 'Confidentialité',
    editLabel: 'Modifier', pwdLabel: 'Mot de passe',
    notifLabel: 'Notifications', dailyReminder: 'Rappel quotidien',
    reminderTime: 'Heure de rappel', soundLabel: 'Sons', soundEffects: 'Effets sonores',
    notifBlocked: 'Notifications bloquées — autorise-les dans les paramètres du navigateur.',
    langLabel: 'Langue', dataLabel: 'Données', exportData: 'Exporter mes données', exportPDF: 'Rapport mensuel PDF',
    historyLabel: 'Historique', deleteHistory: "Supprimer l'historique",
    clearLabel: 'Effacer', deleteAccount: '🗑 Supprimer mon compte',
    deleteTitle: 'Supprimer mon compte ?',
    deleteBody: 'Cette action est irréversible. Toutes tes données seront perdues.',
    deleteConfirm: 'Supprimer',
    navMood: 'Humeur du jour', navCalendar: 'Calendrier', navStats: 'Statistiques',
    navChart: 'Graphique', navAccount: 'Mon compte', navLogout: 'Se déconnecter',
    navCrisis: 'Mode crise', navAbout: 'À propos',
    langValue: 'Français 🇫🇷',
    pwdPlaceholders: ['Mot de passe actuel', 'Nouveau mot de passe', 'Confirmer'],
    themeTitle: 'Thème de l\'app', badgesTitle: 'Mes badges', avatarTitle: 'Mon avatar',
    badgeStarter:    '🌱 Débutant',    badgeStarterDesc:    'Bienvenue dans l\'aventure !',
    badgeStreak3:    '🔥 En route',    badgeStreak3Desc:    '3 jours consécutifs',
    badgeStreak7:    '⚡ Régulier',    badgeStreak7Desc:    '7 jours consécutifs',
    badgeStreak30:   '💎 Engagé·e',   badgeStreak30Desc:   '30 jours consécutifs',
    badgeEntries10:  '🦉 Observateur·rice', badgeEntries10Desc: '10 entrées enregistrées',
    badgeEntries50:  '🌟 Vétéran·e', badgeEntries50Desc:  '50 entrées enregistrées',
    badgeEntries100: '🏆 Légende',    badgeEntries100Desc: '100 entrées enregistrées',
    badgeLocked: 'Verrouillé',
    shareBtn: 'Partager', shareBadgeText: (badge, app) => `Je viens de débloquer le badge ${badge} sur ${app} !`,
    dailyQuotes: [
      'Prendre soin de soi, c\'est déjà beaucoup.',
      'Chaque jour compte, même les gris.',
      'Tu n\'as pas à aller bien tout le temps.',
      'Observer ses émotions, c\'est déjà avancer.',
      'La constance vaut plus que la perfection.',
      'Être là, présent·e, c\'est suffisant.',
      'Ton ressenti est valide, quoi qu\'il soit.',
    ],
    crisisTitle: 'Mode crise',
    crisisSub: 'Tu n\'es pas seul·e. De l\'aide est disponible.',
    crisisCallBtn: 'Appeler',
    crisisEmergencyContact: 'Mon contact de confiance',
    crisisNoContact: 'Aucun contact enregistré',
    crisisAddContact: 'Ajouter un contact',
    crisisContactName: 'Prénom du contact',
    crisisContactPhone: 'Numéro de téléphone',
    crisisResourcesTitle: 'Ressources officielles',
    crisisResourcesSub: 'Liens vers de la documentation et des lignes d\'écoute',
    crisisNumbers: [
      { label: '🇫🇷 Prévention du suicide', number: '3114', desc: 'Numéro national, 24h/24, gratuit' },
      { label: '🚑 SAMU', number: '15', desc: 'Urgences médicales' },
      { label: '🚨 Police / Gendarmerie', number: '17', desc: 'Urgences de sécurité' },
      { label: '🇪🇺 Urgences Europe', number: '112', desc: 'Numéro d\'urgence européen' },
    ],
    crisisResources: [
      { label: '3114 — Prévention du suicide', url: 'https://www.3114.fr' },
      { label: 'Psycom — Santé mentale', url: 'https://www.psycom.org' },
      { label: 'Croix-Rouge écoute', url: 'https://www.croix-rouge.fr/agir/soutien-psychologique' },
    ],
    aboutTitle: 'À propos',
    aboutBody: 'J\'ai créé MoodTracker pour celle qui partage ma vie. Elle vit avec un trouble bipolaire, et parfois les mots sont difficiles à trouver. J\'avais envie de lui offrir un espace rien qu\'à elle — un endroit où poser ses émotions sans jugement, jour après jour, et d\'avoir un suivi qui permet d\'anticiper les crises autant que possible.\n\nCette app est née de l\'amour, pas d\'une startup. Je m\'appelle Florent, je ne suis pas médecin, juste quelqu\'un qui aime et qui essaie d\'aider du mieux qu\'il peut.\n\nSi tu utilises MoodTracker et que ça t\'aide, toi ou un proche, alors ça compte énormément pour moi. Tu n\'es pas seul·e.',
    aboutMadeWith: 'Fait avec ❤️ par Florent',
    aboutVersion: 'Version 1.1',
    installTitle: 'Installer l\'application',
    installSub: 'Ajoute MoodTracker à ton écran d\'accueil pour un accès rapide.',
    installIOSSub: 'Pour installer, appuie sur',
    installIOSAdd: 'Sur l\'écran d\'accueil',
    installBtn: 'Installer',
    installDismiss: 'Plus tard',
    avgSleep: 'Sommeil moyen',
    futureDayBlocked: 'Pas encore !',
    streakDays: 'jours de suite !',
    streakMilestone: (n) => `🔥 ${n} jours de suite !`,
    streakMilestoneSub: 'Nouveau record, continue comme ça !',
  },
  en: {
    welcome: 'Welcome to', appName: 'MoodTracker!',
    welcomeSub: 'Your space to track how you feel every day.',
    login: 'Log in', register: 'Sign up',
    email: 'Email', password: 'Password',
    loginBtn: "I'll feel better ❤️", back: '← Back',
    firstname: 'First name', confirmPwd: 'Confirm password',
    chooseLanguage: 'Choose language / Choisir la langue',
    moodQuestion: 'How are you\nfeeling today?',
    moodHint: 'Select your mood ↑',
    moodHappy: "You're super happy today!",
    moodOk: 'Not bad, things are okay!',
    moodSad: "I'm here to listen.",
    continueBtn: 'Continue →', moreTellBtn: 'Tell me more', confideBtn: 'Open up →',
    tooDayHappy: "You're so happy today",
    alwaysCase: 'as always!', wantMoreInfo: 'want to tell me more?',
    yes: 'Yes', no: 'No',
    listeningTitle: "I'm listening", journalPH: 'Today I...',
    tags: ['Went out', 'Treated myself', 'Slept badly', 'Exercised', 'Went to cinema', 'Good news', 'Went to work', 'Did housework', 'Cooked', 'Saw family', 'Saw friends', 'Time for myself', 'Cried', 'Felt anxious', 'Felt tired', 'Took my meds', 'Meditated', 'Read a book', 'Listened to music'],
    thanksTitle: 'Thanks for sharing',
    thanksSub: 'You can always edit this in the calendar!',
    seeCalendar: 'View calendar', calendarTitle: 'Calendar',
    months: ['January','February','March','April','May','June','July','August','September','October','November','December'],
    days: ['M','T','W','T','F','S','S'],
    legendGood: '🟢 Good', legendOk: '🟡 Okay', legendHard: '🔴 Hard',
    calHint: 'Tap a day to see details',
    editEntry: '✏️ Edit', addEntry: '+ Add',
    noComment: 'No comment', notLogged: 'not logged', close: 'Close',
    editDay: 'Edit day', addComment: 'Add a comment...',
    cancel: 'Cancel', save: 'Save',
    sleepLabel: 'Hours of sleep', sleepQuestion: 'Did you sleep well?', sleepSub: 'How many hours did you sleep last night?', skipBtn: 'Skip', avgSleep: 'Avg sleep',
    foodQuestion: 'How did you eat today?', foodSub: 'Your nutrition for today?',
    foodLabel: 'Nutrition',
    foodOptions: [
      { value: 3, emoji: '🍽️', label: 'Ate well' },
      { value: 2, emoji: '🥗', label: 'Ate a little' },
      { value: 1, emoji: '😔', label: "Didn't eat" },
    ],
    fatigueQuestion: 'How is your energy?', fatigueSub: 'Your fatigue level today?',
    fatigueLabel: 'Energy',
    fatigueOptions: [
      { value: 3, emoji: '⚡', label: 'Not tired' },
      { value: 2, emoji: '😌', label: 'A little tired' },
      { value: 1, emoji: '😓', label: 'Very tired' },
    ],
    statsTitle: 'Statistics', daysTracked: 'Days tracked',
    topMood: 'Top mood', positiveDays: 'Positive days', streak: 'Streak 🔥',
    thisWeek: '😊 Mood this week',
    daysShort: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
    moodLabel: 'Mood',
    avgFoodLabel: 'Nutrition', avgFatigueLabel: 'Energy',
    correlationChart: '📊 Mood & well-being',
    sleepCorrelationPos: '✨ When you sleep more (≥7h), your mood is better. Keep it up!',
    sleepCorrelationNeg: '🤔 Interesting — your mood seems better with less sleep this month.',
    sleepCorrelationNeutral: '📊 No clear link between sleep and mood this month.',
    foodCorrelationPos: '🍽️ When you eat well, your mood tends to be better.',
    foodCorrelationNeg: "🤔 Interesting — your mood seems independent of your diet this month.",
    foodCorrelationNeutral: '📊 No clear link between nutrition and mood this month.',
    fatigueCorrelationPos: "⚡ When you're rested, your mood is better.",
    fatigueCorrelationNeg: "🤔 Your energy level doesn't seem to affect your mood this month.",
    fatigueCorrelationNeutral: '📊 No clear link between energy and mood this month.',
    chartTitle: 'Chart', noData: '📋 Not enough data this month.',
    trendHigh: '📊 Generally high mood this month.',
    trendMid: '📊 Fairly stable mood this month.',
    trendLow: '📊 Some ups and downs this month.',
    trendHard: '📊 A difficult month overall.',
    trendUp: '↗ On the rise over the period.',
    trendDown: '↘ Declining over the period.',
    accountTitle: 'My account', personalInfo: 'Personal info',
    preferences: 'Preferences', privacy: 'Privacy',
    editLabel: 'Edit', pwdLabel: 'Password',
    notifLabel: 'Notifications', dailyReminder: 'Daily reminder',
    reminderTime: 'Reminder time', soundLabel: 'Sounds', soundEffects: 'Sound effects',
    notifBlocked: 'Notifications blocked — allow them in your browser settings.',
    langLabel: 'Language', dataLabel: 'Data', exportData: 'Export my data', exportPDF: 'Monthly PDF report',
    historyLabel: 'History', deleteHistory: 'Delete history',
    clearLabel: 'Clear', deleteAccount: '🗑 Delete my account',
    deleteTitle: 'Delete my account?',
    deleteBody: 'This action is irreversible. All your data will be lost.',
    deleteConfirm: 'Delete',
    navMood: "Today's mood", navCalendar: 'Calendar', navStats: 'Statistics',
    navChart: 'Chart', navAccount: 'My account', navLogout: 'Log out',
    navCrisis: 'Crisis mode', navAbout: 'About',
    langValue: 'English 🇬🇧',
    pwdPlaceholders: ['Current password', 'New password', 'Confirm'],
    themeTitle: 'App theme', badgesTitle: 'My badges', avatarTitle: 'My avatar',
    badgeStarter:    '🌱 Beginner',   badgeStarterDesc:    'Welcome to the journey!',
    badgeStreak3:    '🔥 On a roll',  badgeStreak3Desc:    '3 days in a row',
    badgeStreak7:    '⚡ Consistent', badgeStreak7Desc:    '7 days in a row',
    badgeStreak30:   '💎 Committed',  badgeStreak30Desc:   '30 days in a row',
    badgeEntries10:  '🦉 Observer',   badgeEntries10Desc:  '10 entries logged',
    badgeEntries50:  '🌟 Veteran',    badgeEntries50Desc:  '50 entries logged',
    badgeEntries100: '🏆 Legend',     badgeEntries100Desc: '100 entries logged',
    badgeLocked: 'Locked',
    shareBtn: 'Share', shareBadgeText: (badge, app) => `I just unlocked the ${badge} badge on ${app}!`,
    dailyQuotes: [
      'Taking care of yourself is already a lot.',
      'Every day counts, even the grey ones.',
      'You don\'t have to be okay all the time.',
      'Noticing your emotions is already progress.',
      'Consistency matters more than perfection.',
      'Being present is enough.',
      'Whatever you feel is valid.',
    ],
    crisisTitle: 'Crisis mode',
    crisisSub: 'You are not alone. Help is available.',
    crisisCallBtn: 'Call',
    crisisEmergencyContact: 'My trusted contact',
    crisisNoContact: 'No contact saved',
    crisisAddContact: 'Add a contact',
    crisisContactName: 'Contact name',
    crisisContactPhone: 'Phone number',
    crisisResourcesTitle: 'Official resources',
    crisisResourcesSub: 'Links to helplines and mental health support',
    crisisNumbers: [
      { label: '🇺🇸 Suicide & Crisis Lifeline', number: '988', desc: '24/7, free, call or text' },
      { label: '🚑 Emergency Services', number: '911', desc: 'Police, fire, medical emergencies' },
      { label: '💬 Crisis Text Line', number: 'Text HOME → 741741', desc: 'Text-based crisis support' },
      { label: '🧠 NAMI Helpline', number: '1-800-950-6264', desc: 'Mental health support line' },
      { label: '🇪🇺 European Emergency', number: '112', desc: 'Works in all EU countries' },
    ],
    crisisResources: [
      { label: '988 Suicide & Crisis Lifeline', url: 'https://988lifeline.org' },
      { label: 'NAMI — Mental Health Alliance', url: 'https://www.nami.org' },
      { label: 'Crisis Text Line', url: 'https://www.crisistextline.org' },
    ],
    aboutTitle: 'About',
    aboutBody: 'I built MoodTracker for my partner. She lives with bipolar disorder, and sometimes words are hard to find. I wanted to give her a space that was just hers — somewhere to set down her feelings without judgment, day after day, and to have tracking that helps anticipate episodes as much as possible.\n\nThis app was born out of love, not a startup. My name is Florent. I\'m not a doctor, just someone who loves someone and is doing their best to help.\n\nIf you\'re using MoodTracker and it helps you, or someone you care about, that means everything to me. You are not alone.',
    aboutMadeWith: 'Made with ❤️ by Florent',
    aboutVersion: 'Version 1.1',
    installTitle: 'Install the app',
    installSub: 'Add MoodTracker to your home screen for quick access.',
    installIOSSub: 'To install, tap',
    installIOSAdd: 'Add to Home Screen',
    installBtn: 'Install',
    installDismiss: 'Maybe later',
    avgSleep: 'Avg sleep',
    futureDayBlocked: 'Not yet!',
    streakDays: 'days in a row!',
    streakMilestone: (n) => `🔥 ${n} days in a row!`,
    streakMilestoneSub: 'New record, keep it up!',
  }
}

const LangContext = createContext(null)

export function LangProvider({ children }) {
  const [lang, setLang] = useState('fr')
  const t = (key) => translations[lang][key] ?? key
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
